[package]
name = "alloy-gwyneth-evm"
description = "Gwyneth EVM integration"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
alloy-evm = { workspace = true }
alloy-primitives.workspace = true

revm.workspace = true

# gwyneth engine + related crates
gwyneth-engine = { path = "../../../revm-private/revm-private/gwyneth/crates/gwyneth-engine", default-features = false }
gwyneth-detector = { path = "../../../revm-private/revm-private/gwyneth/crates/gwyneth-detector", default-features = false }
gwyneth-types = { path = "../../../revm-private/revm-private/gwyneth/crates/gwyneth-types", default-features = false }

[dev-dependencies]
either = "1.15.0"
gwyneth-phase64-shared-dev = { path = "../../../gwyneth-private/gwyneth-private/testing/phase64-shared-dev-crate" }

[features]
default = ["std"]
std = [
    "alloy-evm/std",
    "alloy-primitives/std",
    "revm/std",
    "gwyneth-engine/std",
    "gwyneth-detector/std",
    "gwyneth-types/std",
]
